DROP DATABASE IF EXISTS react_db;
CREATE DATABASE react_db;

USE react_db;

CREATE TABLE reactDOM (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  music_name VARCHAR(100) NOT NULL
);

CREATE TABLE reactDOM (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    music_id INT,
    review TEXT NOT NULL,
    FOREIGN KEY (music_id)
    REFERENCES music(id)
    ON DELETE SET NULL
);
